name       : python-moddb
version    : 0.8.1
release    : 2
source     :
    - https://pypi.io/packages/source/m/moddb/moddb-0.8.1.tar.gz : cf103b4cb1d43e4fcf2cd9e64ca030767e946fdce2ddb091ab8808ea04781ab8
license    : MIT
homepage   : https://github.com/ClementJ18/moddb
component  : programming.python
summary    : A scrapper for ModDB Mod and Game pages
description: |
    The goal of this library is to be able to navigate ModDB purely programmatically through scraping and parsing of the various models present on the website.
rundeps    :
    - python-beautifulsoup4
    - python-pyrate-limiter
    - python-requests
    - python-toolz
setup      : |
    %apply_patches
build      : |
    %python3_setup
install    : |
    %python3_install
